// src/components/Field/Piece/Piece.tsx
import React, { FC } from 'react';
import PieceModel, { PieceColor } from '../../../model/Piece';
import './Piece.css';

interface PieceProps {
  piece: PieceModel | null;
}

const Piece: FC<PieceProps> = function (props) {
  return (
    <div
      className={
        'Piece ' +
        (props.piece
          ? props.piece.owner === 0
            ? PieceColor.BLACK
            : PieceColor.WHITE
          : 'transparent')
      }></div>
  );
};

export default Piece;

// src/app/component/piece/piece.component.ts
import { Component, Input } from '@angular/core';
import { Piece, PieceColor } from '@model/piece.model';

@Component({
  selector: 'app-piece',
  templateUrl: 'piece.component.html',
  styleUrls: ['piece.component.css']
})
export class PieceComponent {

  @Input() piece!: Piece;

  constructor() { }

  getColor() {
    if (this.piece.owner === 0) {
      return PieceColor.BLACK;
    } else if (this.piece.owner === 1) {
      return PieceColor.WHITE;
    } else {
      return PieceColor.INVALID;
    }
  }

}

<div class="piece {{ getColor() }}"></div>
